apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: board-game-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/boardgame-k8s.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
