apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: apoorvar12/board-game:34
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: boardgame-ssvc
  namespace: default
spec:
  type: NodePort
  selector:
    app: boardgame
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
